-- 024: Seed curated public-domain / traditional quotes (idempotent)
-- Korean text: app-internal short translations of classical/folk sources.
-- Prefer scripts/seed-public-domain-quotes.mjs for live DB apply + embeddings.

-- Applied via seed script; this migration documents the policy and ensures
-- fresh environments can load the same corpus when SQL is preferred.
-- Full corpus lives in scripts/seed-public-domain-quotes.mjs (source of truth).

-- Keep a representative subset here for migration-only environments.
insert into public.quote_library (
  quote_text_ko,
  original_text,
  author_name,
  work_title,
  publication_info,
  source_type,
  translator,
  language,
  themes_json,
  emotional_tone_json,
  suitable_states_json,
  unsuitable_states_json,
  rights_status,
  verification_status,
  attribution_confidence,
  active,
  reviewed_by,
  reviewed_at
)
select * from (values
  (
    '시작이 일의 절반이다',
    'Dimidium facti qui coepit habet',
    '호라티우스',
    '서간집',
    'Public-domain Latin; Korean app-internal seed translation',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["시작","실행","용기"]'::jsonb,
    '["격려","단호"]'::jsonb,
    '["불안","망설임"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.85,
    true,
    'migration-024',
    now()
  ),
  (
    '천천히 가도 꾸준히 가라',
    'Festina lente',
    '라틴 전통 격언',
    '전통 귀속 격언',
    'Public-domain Latin proverb; Korean app-internal seed translation',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["균형","인내","실행"]'::jsonb,
    '["차분","인정"]'::jsonb,
    '["불안","지침"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.85,
    true,
    'migration-024',
    now()
  ),
  (
    '천 리 길도 한 걸음부터',
    null,
    '한국 전통 속담',
    '민속 전승 속담',
    'Korean folk proverb; public domain tradition',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["시작","인내","실행"]'::jsonb,
    '["격려","차분"]'::jsonb,
    '["망설임","지침"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.9,
    true,
    'migration-024',
    now()
  ),
  (
    '고생 끝에 낙이 온다',
    null,
    '한국 전통 속담',
    '민속 전승 속담',
    'Korean folk proverb; public domain tradition',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["희망","인내","회복"]'::jsonb,
    '["위로","격려"]'::jsonb,
    '["지침","슬픔","불안"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.9,
    true,
    'migration-024',
    now()
  ),
  (
    '비 온 뒤에 땅이 굳어진다',
    null,
    '한국 전통 속담',
    '민속 전승 속담',
    'Korean folk proverb; public domain tradition',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["회복","성장","인내"]'::jsonb,
    '["위로","격려"]'::jsonb,
    '["슬픔","지침","불안"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.9,
    true,
    'migration-024',
    now()
  ),
  (
    '실패는 성공의 어머니',
    null,
    '한국 전통 속담',
    '민속 전승 속담',
    'Korean folk proverb; public domain tradition',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["회복","배움","성장"]'::jsonb,
    '["위로","격려"]'::jsonb,
    '["슬픔","지침","불안"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.85,
    true,
    'migration-024',
    now()
  ),
  (
    '티끌 모아 태산',
    null,
    '한국 전통 속담',
    '민속 전승 속담',
    'Korean folk proverb; public domain tradition',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["성실","인내","성장"]'::jsonb,
    '["격려","차분"]'::jsonb,
    '["지침","망설임"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.9,
    true,
    'migration-024',
    now()
  ),
  (
    '밤이 가장 어두울 때 새벽이 가깝다',
    'The darkest hour is just before the dawn',
    '전통 영미 속담',
    '민속 전승 격언',
    'English folk proverb; Korean app-internal seed translation',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["희망","회복","인내"]'::jsonb,
    '["위로","격려"]'::jsonb,
    '["슬픔","지침","불안"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.7,
    true,
    'migration-024',
    now()
  ),
  (
    '네 자신을 알라',
    'γνῶθι σεαυτόν',
    '델포이 신탁 (전통)',
    '아폴론 신전 격언',
    'Classical Greek maxim; Korean app-internal seed translation',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["자기이해","성찰","진정성"]'::jsonb,
    '["성찰","단호"]'::jsonb,
    '["불안","망설임"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.85,
    true,
    'migration-024',
    now()
  ),
  (
    '말보다 행동이 중요하다',
    'Actions speak louder than words',
    '전통 영미 속담',
    '민속 전승 격언',
    'English folk proverb; Korean app-internal seed translation',
    'public_domain_tradition',
    'app_internal_ko',
    'ko',
    '["실행","성실","진정성"]'::jsonb,
    '["단호","격려"]'::jsonb,
    '["망설임","답답함"]'::jsonb,
    '[]'::jsonb,
    'public_domain',
    'reputable_secondary_verified',
    0.8,
    true,
    'migration-024',
    now()
  )
) as v(
  quote_text_ko,
  original_text,
  author_name,
  work_title,
  publication_info,
  source_type,
  translator,
  language,
  themes_json,
  emotional_tone_json,
  suitable_states_json,
  unsuitable_states_json,
  rights_status,
  verification_status,
  attribution_confidence,
  active,
  reviewed_by,
  reviewed_at
)
where not exists (
  select 1
  from public.quote_library q
  where q.quote_text_ko = v.quote_text_ko
    and coalesce(q.author_name, '') = coalesce(v.author_name, '')
);

comment on table public.quote_library is
  'Verified quote corpus. Full seed: scripts/seed-public-domain-quotes.mjs; subset: migration 024.';
